# This is a basic workflow to help you get started with Actions

name: KPT Nightly

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.14

      - uses: actions/checkout@v2.3.3
        with:
          repository: GoogleContainerTools/kpt
          path: kpt
          
      - uses: actions/checkout@v2.3.3
        with:
          repository: kubernetes-sigs/kustomize
          path: kustomize
          
      - name: Replace modules
        shell: bash
        working-directory: ./kpt
        run: echo -e "replace sigs.k8s.io/kustomize/cmd/config => ../kustomize/cmd/config\nreplace sigs.k8s.io/kustomize/kyaml => ../kustomize/kyaml" >> go.mod; cat go.mod
      
      - name: Run test
        shell: bash
        working-directory: ./kpt
        run: make test
      
